#!/bin/bash

# Obfuscate the obfuscator as a torture test
# ./pyobfuscate xxx.py >> xxx_rename.py

../pyobfuscate ../pyobfuscate > pyobfuscate
chmod u+x pyobfuscate

for fn in test_*.py; do
	./pyobfuscate $fn | python -
done
